/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.OpenSimulationController;
import Model.Simulation;
import System.Error;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LAPR3_20152016_G27
 */
public class OpenSimulationGUI extends GraphicUserInterface {

	private DefaultListModel jModelListProjects = new DefaultListModel();
	private OpenSimulationController openProjectController = new OpenSimulationController();

	/**
	 * Creates new form OpenProjectGUI
	 *
	 * @param origin
	 */
	public OpenSimulationGUI(GraphicUserInterface origin) {
		this.initComponents();
		this.creation(origin);
	}

	@Override
	public void initiation() {
		this.jListSimulation.setModel(jModelListProjects);
		this.openProjectController.initiation();
	}

	@Override
	public void update() {
		this.jModelListProjects.removeAllElements();
		for (Simulation object : this.openProjectController.getSimulations()) {
			this.jModelListProjects.addElement(object);
		}
		this.active(!this.jModelListProjects.isEmpty());
	}

	public Boolean active(Boolean state) {
		this.jListSimulation.setEnabled(state);
		this.jButtonOpen.
			setEnabled(this.jListSimulation.getSelectedIndex() != -1);
		return state;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListSimulation = new javax.swing.JList();
        jLabelProjects = new javax.swing.JLabel();
        jButtonOpen = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 220));

        jListSimulation.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSimulationValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListSimulation);

        jLabelProjects.setText("List of Simulation:");

        jButtonOpen.setText("Open");
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		this.close();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
		if (jListSimulation.getSelectedIndex() != -1) {
			Simulation Simulation = (Simulation) jListSimulation.
				getSelectedValue();
			if (this.openProjectController.openSimulation(Simulation)) {
				JOptionPane.
					showMessageDialog(this, "Open project successfully!");
				this.close();
			} else {
				JOptionPane.
					showMessageDialog(this, "Error opening project: " + Error.
									  getErrorMessage());
			}
		}
    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
		this.openProjectController.initiation();
		this.update();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jListSimulationValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSimulationValueChanged
		this.jButtonOpen.
			setEnabled(this.jListSimulation.getSelectedIndex() != -1);
    }//GEN-LAST:event_jListSimulationValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelProjects;
    private javax.swing.JList jListSimulation;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
