/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template fileChooser, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.RunSimulationController;
import Simulation.AnalysisMethod;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LAPR3_20152016_G27
 */
public class RunSimulationGUI extends GraphicUserInterface {

	private RunSimulationController runSimulationController = new RunSimulationController();
	private DefaultComboBoxModel jModelComboBoxAnalysisMethod = new DefaultComboBoxModel();
	private List<AnalysisMethod> analysisMethods;

	/**
	 * Creates new form CreateProjectGUI
	 *
	 * @param origin
	 */
	public RunSimulationGUI(GraphicUserInterface origin) {
		this.initComponents();
		this.creation(origin);
	}

	/**
	 *
	 */
	@Override
	public void initiation() {
		this.runSimulationController.initiation();
		this.analysisMethods = this.runSimulationController.getAnalysisMethods();
		this.jComboBoxAnalysisMethod.setModel(this.jModelComboBoxAnalysisMethod);
		this.jModelComboBoxAnalysisMethod.removeAllElements();
		for (AnalysisMethod analysisMethod : this.runSimulationController.
			getAnalysisMethods()) {
			this.jModelComboBoxAnalysisMethod.addElement(analysisMethod);
		}
		this.jComboBoxDurationType.setSelectedIndex(-1);
		this.jComboBoxTimeStepType.setSelectedIndex(-1);
		this.jComboBoxAnalysisMethod.setSelectedIndex(-1);
		this.jTextFieldName.setText("");
		this.jTextFieldDuration.setText("");
		this.jTextFieldTimeStep.setText("");
	}

	/**
	 *
	 */
	@Override
	public void update() {
		if (this.runSimulationController.getActive()) {
			this.jButtonRun.setText("Stop");
			this.jButtonPause.setEnabled(true);
			this.active(false);
			if (this.runSimulationController.getPause()) {
				this.jButtonPause.setText("Continue");
			} else {
				this.jButtonPause.setText("Pause");
			}
		} else {
			this.active(true);
			this.jButtonRun.setText("Run");
			this.jButtonPause.setEnabled(false);
			this.jButtonPause.setText("Pause");
		}

		// TEMPORARIO
		this.jTextFieldName.setText("Meu Run");
		this.jTextFieldDuration.setText("3");
		this.jTextFieldTimeStep.setText("10");
		this.jComboBoxDurationType.setSelectedIndex(0);
		this.jComboBoxTimeStepType.setSelectedIndex(0);
		this.jComboBoxAnalysisMethod.setSelectedIndex(0);
	}

	/**
	 *
	 * @param state
	 * @return
	 */
	public Boolean active(Boolean state) {
		this.jButtonClean.setEnabled(state);
		this.jTextFieldName.setEnabled(state);
		this.jTextFieldDuration.setEnabled(state);
		this.jTextFieldTimeStep.setEnabled(state);
		this.jComboBoxDurationType.setEnabled(state);
		this.jComboBoxTimeStepType.setEnabled(state);
		this.jComboBoxAnalysisMethod.setEnabled(state);
		return state;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRun = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldDuration = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelDuration = new javax.swing.JLabel();
        jButtonClean = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jComboBoxDurationType = new javax.swing.JComboBox();
        jLabelTimeStep = new javax.swing.JLabel();
        jTextFieldTimeStep = new javax.swing.JTextField();
        jComboBoxTimeStepType = new javax.swing.JComboBox();
        jLabelAnalysisMethod = new javax.swing.JLabel();
        jComboBoxAnalysisMethod = new javax.swing.JComboBox();
        jButtonPause = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 400, 200));
        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));

        jButtonRun.setText("Start");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabelDuration.setText("Duration:");

        jButtonClean.setText("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jComboBoxDurationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "second (s)", "minutes (min)", "hours (h)" }));

        jLabelTimeStep.setText("Time Step:");

        jComboBoxTimeStepType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "second (s)", "minutes (min)", "hours (h)" }));

        jLabelAnalysisMethod.setText("Analysis Method:");

        jButtonPause.setText("Pause");
        jButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRun)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jButtonClean)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelDuration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDuration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDurationType, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTimeStep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTimeStep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTimeStepType, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAnalysisMethod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAnalysisMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDuration)
                    .addComponent(jComboBoxDurationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTimeStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTimeStep)
                    .addComponent(jComboBoxTimeStepType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAnalysisMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnalysisMethod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClean)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonRun)
                    .addComponent(jButtonPause))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
		if (this.runSimulationController.getActive()) {
			this.runSimulationController.setActive(false);
			//JOptionPane.showMessageDialog(this, "Simulation needs a name!");
		} else {
			if (!this.jTextFieldName.getText().isEmpty() || !this.jTextFieldDuration.
				getText().isEmpty() || !this.jTextFieldTimeStep.getText().
				isEmpty() || this.jComboBoxDurationType.getSelectedIndex() != -1 || this.jComboBoxTimeStepType.
				getSelectedIndex() != -1 || this.jComboBoxAnalysisMethod.
				getSelectedIndex() != -1) {
				String time = this.jTextFieldDuration.getText();
				if (this.jComboBoxDurationType.getSelectedIndex() == 0) {
					time += " s";
				} else if (this.jComboBoxDurationType.getSelectedIndex() == 1) {
					time += " min";
				} else if (this.jComboBoxDurationType.getSelectedIndex() == 2) {
					time += " h";
				}
				String timeStep = this.jTextFieldDuration.getText();
				if (this.jComboBoxTimeStepType.getSelectedIndex() == 0) {
					timeStep += " s";
				} else if (this.jComboBoxTimeStepType.getSelectedIndex() == 1) {
					timeStep += " min";
				} else if (this.jComboBoxTimeStepType.getSelectedIndex() == 2) {
					timeStep += " h";
				}
				System.out.println(time);
				System.out.println(timeStep);
				if (this.runSimulationController.run(this.jTextFieldName.
					getText(), time, timeStep, this.jComboBoxAnalysisMethod.
													 getSelectedIndex())) {
					this.runSimulationController.setActive(true);
				} else {
					JOptionPane.
						showMessageDialog(this, "It is only accept numbers in the times!");
				}
			} else {
				JOptionPane.
					showMessageDialog(this, "It must fill all data to run the simulation!");
			}
		}
		this.update();
    }//GEN-LAST:event_jButtonRunActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		if (this.runSimulationController.getActive()) {
			this.runSimulationController.setActive(false);
		} else {
			this.close();
		}
		this.update();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
		this.initiation();
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauseActionPerformed
		if (this.runSimulationController.getPause()) {
			this.runSimulationController.setPause(false);
		} else {
			this.runSimulationController.setPause(true);
		}
		this.update();
    }//GEN-LAST:event_jButtonPauseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JComboBox jComboBoxAnalysisMethod;
    private javax.swing.JComboBox jComboBoxDurationType;
    private javax.swing.JComboBox jComboBoxTimeStepType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnalysisMethod;
    private javax.swing.JLabel jLabelDuration;
    private javax.swing.JLabel jLabelTimeStep;
    private javax.swing.JTextField jTextFieldDuration;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldTimeStep;
    // End of variables declaration//GEN-END:variables
}
