/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ContextController;
import Controller.VehicleAnalysisController;
import Model.Node;
import Model.Vehicle;
import Simulation.VehicleAnalysis;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LAPR3_20152016_G27
 */
public class VehicleAnalysisGUI extends GraphicUserInterface {

	private VehicleAnalysisController vehicleComparisonController = new VehicleAnalysisController();
	private DefaultComboBoxModel jModelComboBoxStartNodes = new DefaultComboBoxModel();
	private DefaultListModel jModelListEndNodes = new DefaultListModel();
	private DefaultListModel jModelListVehicles = new DefaultListModel();

	/**
	 * Creates new form VehicleComparisonGUI
	 */
	public VehicleAnalysisGUI(GraphicUserInterface orign,
							  VehicleAnalysis vehicleAnalysis) {
		this.initComponents();
		this.creation(orign);
		this.vehicleComparisonController.setVehicleAnalysis(vehicleAnalysis);
	}

	@Override
	public void initiation() {
		this.vehicleComparisonController.initiation();
		jListVehicles.setModel(jModelListVehicles);
		for (Vehicle vec : ContextController.getOpenProject().getVehicles()) {
			jModelListVehicles.addElement(vec);
		}
		jListVehicles.setEnabled(true);
		this.jComboBoxStartNodes.setModel(this.jModelComboBoxStartNodes);
		this.jListEndNodes.setModel(this.jModelListEndNodes);
		for (Node node : this.vehicleComparisonController.getNodes()) {
			this.jModelComboBoxStartNodes.addElement(node);
		}
		this.jButtonCleanActionPerformed(null);
	}

	@Override
	void update() {
		this.jModelListEndNodes.removeAllElements();
		for (Node node : this.vehicleComparisonController.getNodes()) {
			if (!node.equals((Node) this.jComboBoxStartNodes.
				getSelectedItem())) {
				this.jModelListEndNodes.addElement(node);
			}
		}
		this.active(true);
	}

	public Boolean active(Boolean state) {
		this.jButtonAnalyze.setEnabled(this.jComboBoxStartNodes.
			getSelectedIndex() != -1 && this.jListEndNodes.getSelectedIndex() != -1 && this.jListVehicles.
			getSelectedIndex() != -1);
		return state;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWithStartNodes = new javax.swing.JLabel();
        jComboBoxStartNodes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabelWithEndNodes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListVehicles = new javax.swing.JList();
        jLabelWithVehicles = new javax.swing.JLabel();
        jButtonAnalyze = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEndNodes = new javax.swing.JList();
        jButtonClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 270));

        jLabelWithStartNodes.setText("Select Start Node:");

        jComboBoxStartNodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStartNodesActionPerformed(evt);
            }
        });

        jLabelWithEndNodes.setText("Select End Nodes:");

        jListVehicles.setEnabled(false);
        jListVehicles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListVehiclesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListVehicles);

        jLabelWithVehicles.setText("Select Vehicles: ");

        jButtonAnalyze.setText("Analyze");
        jButtonAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalyzeActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jListEndNodes.setEnabled(false);
        jListEndNodes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEndNodesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListEndNodes);
        jListEndNodes.getAccessibleContext().setAccessibleName("");

        jButtonClean.setLabel("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxStartNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelWithEndNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelWithStartNodes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAnalyze)
                        .addGap(115, 115, 115)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClean)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWithVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWithVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWithStartNodes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxStartNodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelWithEndNodes)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancel)
                            .addComponent(jButtonClean)
                            .addComponent(jButtonAnalyze))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxStartNodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStartNodesActionPerformed
		if (jComboBoxStartNodes.getSelectedIndex() != -1) {
			jListEndNodes.setEnabled(true);
		}
		this.update();
    }//GEN-LAST:event_jComboBoxStartNodesActionPerformed

    private void jButtonAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalyzeActionPerformed
		vehicleComparisonController.
			setNodes((Node) jComboBoxStartNodes.getSelectedItem(), (List<Node>) jListEndNodes.
					 getSelectedValuesList(), (List<Vehicle>) jListVehicles.
					 getSelectedValuesList());
		List<List<String[]>> results = this.vehicleComparisonController.
			analyze();
		if (results != null && !results.isEmpty()) {
			for (List<String[]> result : results) {
				new ResultsGUI(null, result);
			}
		} else {
			JOptionPane.
				showMessageDialog(this, "There is no link between selected data!");
		}
    }//GEN-LAST:event_jButtonAnalyzeActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		this.close();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jListVehiclesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListVehiclesValueChanged
		this.active(true);
    }//GEN-LAST:event_jListVehiclesValueChanged

    private void jListEndNodesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEndNodesValueChanged
		this.active(true);
    }//GEN-LAST:event_jListEndNodesValueChanged

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
		this.jComboBoxStartNodes.setSelectedIndex(-1);
		this.jListEndNodes.setSelectedIndex(-1);
		this.jListVehicles.setSelectedIndex(-1);
		this.update();
    }//GEN-LAST:event_jButtonCleanActionPerformed

	/**
	 * @param args the command line arguments
	 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalyze;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JComboBox jComboBoxStartNodes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelWithEndNodes;
    private javax.swing.JLabel jLabelWithStartNodes;
    private javax.swing.JLabel jLabelWithVehicles;
    private javax.swing.JList jListEndNodes;
    private javax.swing.JList jListVehicles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
